### ISSUE TITLE
Cannot connect to postgresql version 15

### ISSUE THREAD

**Issue by anshour** [fly-apps/laravel-docker#5]
I use neon tech postgres sql to power my laravel app, neon tech uses pgsql version 15. but when i deploy it to the fly, it doesnt work, the error says:
 {"message":"SQLSTATE[08006] [7] ERROR: Endpoint ID is not specified. Either please upgrade the postgres client library (libpq) for SNI support or pass the endpoint ID (first part of the domain name) as a parameter: '?options=endpoint%3D<endpoint-id>'. See more at https://neon.tech/sni\nERROR: connection is insecure (try using `sslmode=require`)","context":{"exception":{"class":"PDOException","message":"SQLSTATE[08006] [7] ERROR: Endpoint ID is not specified. Either please upgrade the postgres client library (libpq) for SNI support or pass the endpoint ID (first part of the domain name) as a parameter: '?options=endpoint%3D<endpoint-id>'
 
 ----
on my windows machine, i simply replace libpq.dll (in php directory ) to the new libpq.dll that i get from postgres installation.
i dont know how to do it via docker. please helpp thanks

**Comment by fideloper** [comment]
Hello from ~4 months later (sorry!) 

This type of customization is something you'll need to do in the final Docker image  you create.

That being said, it might just resolve itself when I update the base image from 20.04 to 22.04.
